package com.agoessling.swingcapture;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashSet;
import java.util.HexFormat;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.zip.CRC32;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/** Creates a bounded, transportable, token-free diagnostic archive for one published session. */
public final class SessionDiagnosticArchive {
  public static final String EXPORT_MANIFEST_NAME = "diagnostic_export.json";
  public static final int MAXIMUM_FILE_COUNT = 128;
  public static final long MAXIMUM_TOTAL_BYTES = 128L * 1024 * 1024;
  private static final int COPY_BUFFER_BYTES = 64 * 1024;
  private static final Set<String> EXCLUDED_NAMES =
      Set.of("diagnostics.zip", "diagnostics.zip.tmp");

  public record Result(File archive, int fileCount, long sourceBytes, long archiveBytes) {
    public Result {
      Objects.requireNonNull(archive, "archive");
      if (fileCount <= 0 || sourceBytes < 0 || archiveBytes <= 0) {
        throw new IllegalArgumentException("diagnostic archive result is invalid");
      }
    }
  }

  private record Source(
      File file,
      byte[] generatedContents,
      String archivePath,
      long bytes,
      long crc32,
      String sha256) {
    private Source {
      if ((file == null) == (generatedContents == null)) {
        throw new IllegalArgumentException("archive source must be either a file or generated bytes");
      }
    }
  }

  private SessionDiagnosticArchive() {}

  public static synchronized Result create(
      File sessionDirectory, File destination, Instant createdAt) throws IOException {
    return create(sessionDirectory, destination, createdAt, Map.of());
  }

  public static synchronized Result create(
      File sessionDirectory,
      File destination,
      Instant createdAt,
      Map<String, byte[]> supplementalFiles)
      throws IOException {
    Objects.requireNonNull(sessionDirectory, "sessionDirectory");
    Objects.requireNonNull(destination, "destination");
    Objects.requireNonNull(createdAt, "createdAt");
    Objects.requireNonNull(supplementalFiles, "supplementalFiles");
    validateSessionDirectory(sessionDirectory);
    File destinationParent = validateDestination(sessionDirectory, destination);

    List<Source> sources = new ArrayList<>(inspectSources(sessionDirectory));
    for (Map.Entry<String, byte[]> supplemental : supplementalFiles.entrySet()) {
      String path = Objects.requireNonNull(supplemental.getKey(), "supplemental path");
      byte[] contents = Objects.requireNonNull(supplemental.getValue(), "supplemental contents");
      validateArchivePath(path);
      if (path.equals(EXPORT_MANIFEST_NAME)) {
        throw new IllegalArgumentException("supplemental path is reserved for the export manifest");
      }
      if (contents.length == 0) {
        throw new IOException("Supplemental diagnostic artifact cannot be empty");
      }
      sources.add(inspectGeneratedSource(path, contents));
    }
    sources.sort(Comparator.comparing(Source::archivePath));
    requireUniquePaths(sources);
    long sourceBytes = boundedSourceBytes(sources);
    if (sources.size() > MAXIMUM_FILE_COUNT) {
      throw new IOException("Diagnostic archive exceeds its configured bounds");
    }
    byte[] manifest = exportManifest(sessionDirectory.getName(), createdAt, sources);
    File temporary = new File(destinationParent, destination.getName() + ".tmp");
    if (temporary.exists() && !temporary.isFile()) {
      throw new IOException("Diagnostic archive temporary path is not a file");
    }
    Files.deleteIfExists(temporary.toPath());
    try {
      try (FileOutputStream fileOutput = new FileOutputStream(temporary);
          BufferedOutputStream buffered = new BufferedOutputStream(fileOutput);
          ZipOutputStream zip = new ZipOutputStream(buffered)) {
        addBytes(zip, EXPORT_MANIFEST_NAME, manifest);
        byte[] buffer = new byte[COPY_BUFFER_BYTES];
        for (Source source : sources) {
          addSource(zip, source, buffer);
        }
        zip.finish();
        buffered.flush();
        fileOutput.getFD().sync();
      }
      atomicReplace(temporary, destination);
    } finally {
      Files.deleteIfExists(temporary.toPath());
    }
    return new Result(destination, sources.size(), sourceBytes, destination.length());
  }

  private static File validateDestination(File sessionDirectory, File destination)
      throws IOException {
    if (!destination.getName().matches("[A-Za-z0-9][A-Za-z0-9._-]*\\.zip")
        || Files.isSymbolicLink(destination.toPath())
        || (destination.exists() && !destination.isFile())) {
      throw new IOException("Diagnostic archive destination filename is unsafe");
    }
    File requestedParent = destination.getAbsoluteFile().getParentFile();
    if (requestedParent == null) {
      throw new IOException("Diagnostic archive destination has no parent");
    }
    if (!requestedParent.isDirectory() && !requestedParent.mkdirs()) {
      throw new IOException("Unable to create diagnostic archive cache directory");
    }
    if (Files.isSymbolicLink(requestedParent.toPath())) {
      throw new IOException("Diagnostic archive cache directory cannot be a symbolic link");
    }
    File destinationParent = requestedParent.getCanonicalFile();
    File canonicalDestination = new File(destinationParent, destination.getName());
    if (canonicalDestination
        .getCanonicalPath()
        .startsWith(sessionDirectory.getCanonicalPath() + File.separator)) {
      throw new IOException("Diagnostic archive destination must be outside the session");
    }
    return destinationParent;
  }

  private static void validateSessionDirectory(File sessionDirectory) throws IOException {
    if (!sessionDirectory.isDirectory()
        || Files.isSymbolicLink(sessionDirectory.toPath())
        || !sessionDirectory.getName().matches("[A-Za-z0-9._-]+")
        || !new File(sessionDirectory, "manifest.json").isFile()) {
      throw new IOException("Diagnostic source is not a published session directory");
    }
  }

  private static List<Source> inspectSources(File sessionDirectory) throws IOException {
    List<File> files = new ArrayList<>();
    collectFiles(sessionDirectory, sessionDirectory, files);
    if (files.isEmpty() || files.size() > MAXIMUM_FILE_COUNT) {
      throw new IOException("Diagnostic session file count is outside the configured bound");
    }
    List<Source> result = new ArrayList<>(files.size());
    long totalBytes = 0;
    for (File file : files) {
      long bytes = file.length();
      if (bytes < 0 || totalBytes > MAXIMUM_TOTAL_BYTES - bytes) {
        throw new IOException("Diagnostic session byte count exceeds the configured bound");
      }
      totalBytes += bytes;
      String relative;
      try {
        relative = relativePath(sessionDirectory, file);
      } catch (IllegalArgumentException unsafePath) {
        throw new IOException("Diagnostic session contains an unsafe filename", unsafePath);
      }
      result.add(inspectSource(file, sessionDirectory.getName() + "/" + relative, bytes));
    }
    result.sort(Comparator.comparing(Source::archivePath));
    return List.copyOf(result);
  }

  private static void collectFiles(File root, File current, List<File> files) throws IOException {
    if (Files.isSymbolicLink(current.toPath())) {
      throw new IOException("Refusing to archive a symbolic link");
    }
    if (current.getName().equals(SessionStagingCleanup.OWNERSHIP_MARKER)) {
      File parent = current.getAbsoluteFile().getParentFile();
      if (current.isFile()
          && parent != null
          && parent.getCanonicalFile().equals(root.getCanonicalFile())) {
        return;
      }
      throw new IOException(
          "Diagnostic session ownership marker is nested or is not a regular root file");
    }
    if (current.isFile()) {
      if (!EXCLUDED_NAMES.contains(current.getName()) && !current.getName().endsWith(".tmp")) {
        files.add(current);
      }
      return;
    }
    if (!current.isDirectory()) {
      throw new IOException("Diagnostic session contains a non-file entry");
    }
    File[] children = current.listFiles();
    if (children == null) {
      throw new IOException("Unable to enumerate diagnostic session");
    }
    for (File child : children) {
      if (!child.getCanonicalPath().startsWith(root.getCanonicalPath() + File.separator)) {
        throw new IOException("Diagnostic session entry escapes its root");
      }
      collectFiles(root, child, files);
      if (files.size() > MAXIMUM_FILE_COUNT) {
        throw new IOException("Diagnostic session file count exceeds the configured bound");
      }
    }
  }

  private static Source inspectSource(File file, String archivePath, long bytes)
      throws IOException {
    CRC32 crc = new CRC32();
    MessageDigest digest;
    try {
      digest = MessageDigest.getInstance("SHA-256");
    } catch (NoSuchAlgorithmException impossible) {
      throw new IllegalStateException("SHA-256 is unavailable", impossible);
    }
    byte[] buffer = new byte[COPY_BUFFER_BYTES];
    try (InputStream input = new BufferedInputStream(new FileInputStream(file))) {
      int count;
      while ((count = input.read(buffer)) >= 0) {
        if (count == 0) {
          continue;
        }
        crc.update(buffer, 0, count);
        digest.update(buffer, 0, count);
      }
    }
    return new Source(
        file,
        null,
        archivePath,
        bytes,
        crc.getValue(),
        HexFormat.of().formatHex(digest.digest()));
  }

  private static Source inspectGeneratedSource(String archivePath, byte[] contents) {
    byte[] detachedContents = contents.clone();
    CRC32 crc = new CRC32();
    crc.update(detachedContents);
    MessageDigest digest;
    try {
      digest = MessageDigest.getInstance("SHA-256");
    } catch (NoSuchAlgorithmException impossible) {
      throw new IllegalStateException("SHA-256 is unavailable", impossible);
    }
    return new Source(
        null,
        detachedContents,
        archivePath,
        detachedContents.length,
        crc.getValue(),
        HexFormat.of().formatHex(digest.digest(detachedContents)));
  }

  private static String relativePath(File root, File file) {
    String relative = root.toPath().relativize(file.toPath()).toString().replace(File.separatorChar, '/');
    if (relative.isEmpty() || relative.startsWith("/") || relative.contains("../")) {
      throw new IllegalArgumentException("unsafe diagnostic archive entry path");
    }
    validateArchivePath(relative);
    return relative;
  }

  private static void validateArchivePath(String path) {
    if (path.isEmpty() || path.startsWith("/") || path.endsWith("/") || path.contains("//")) {
      throw new IllegalArgumentException("unsafe diagnostic archive entry path");
    }
    for (String segment : path.split("/")) {
      if (segment.isEmpty() || segment.equals(".") || segment.equals("..")) {
        throw new IllegalArgumentException("unsafe diagnostic archive entry path");
      }
      if (segment.endsWith(".tmp")) {
        throw new IllegalArgumentException("temporary filenames cannot be archived");
      }
      for (int index = 0; index < segment.length(); ++index) {
        char value = segment.charAt(index);
        if (!(value >= 'a' && value <= 'z')
            && !(value >= 'A' && value <= 'Z')
            && !(value >= '0' && value <= '9')
            && value != '.'
            && value != '_'
            && value != '-') {
          throw new IllegalArgumentException("unsafe diagnostic archive entry path");
        }
      }
    }
  }

  private static void requireUniquePaths(List<Source> sources) throws IOException {
    Set<String> paths = new HashSet<>();
    for (Source source : sources) {
      if (!paths.add(source.archivePath())) {
        throw new IOException("Diagnostic archive contains a duplicate path");
      }
    }
  }

  private static long boundedSourceBytes(List<Source> sources) throws IOException {
    long total = 0;
    for (Source source : sources) {
      if (source.bytes() < 0 || total > MAXIMUM_TOTAL_BYTES - source.bytes()) {
        throw new IOException("Diagnostic archive exceeds its configured byte bound");
      }
      total += source.bytes();
    }
    return total;
  }

  private static byte[] exportManifest(String sessionId, Instant createdAt, List<Source> sources) {
    StringBuilder json = new StringBuilder(1_024);
    json.append("{\"schema_version\":1,\"session_id\":");
    appendJsonString(json, sessionId);
    json.append(",\"created_at_utc\":");
    appendJsonString(json, createdAt.toString());
    json.append(",\"files\":[");
    for (int index = 0; index < sources.size(); ++index) {
      if (index != 0) {
        json.append(',');
      }
      Source source = sources.get(index);
      json.append("{\"path\":");
      appendJsonString(json, source.archivePath());
      json.append(",\"bytes\":").append(source.bytes());
      json.append(",\"sha256\":");
      appendJsonString(json, source.sha256());
      json.append('}');
    }
    json.append("]}\n");
    return json.toString().getBytes(StandardCharsets.UTF_8);
  }

  private static void appendJsonString(StringBuilder output, String value) {
    output.append('"');
    for (int index = 0; index < value.length(); ++index) {
      char character = value.charAt(index);
      switch (character) {
        case '"' -> output.append("\\\"");
        case '\\' -> output.append("\\\\");
        case '\b' -> output.append("\\b");
        case '\f' -> output.append("\\f");
        case '\n' -> output.append("\\n");
        case '\r' -> output.append("\\r");
        case '\t' -> output.append("\\t");
        default -> {
          if (character < 0x20) {
            output.append(
                String.format(java.util.Locale.ROOT, "\\u%04x", (int) character));
          } else {
            output.append(character);
          }
        }
      }
    }
    output.append('"');
  }

  private static void addBytes(ZipOutputStream zip, String name, byte[] contents)
      throws IOException {
    CRC32 crc = new CRC32();
    crc.update(contents);
    ZipEntry entry = storedEntry(name, contents.length, crc.getValue());
    zip.putNextEntry(entry);
    zip.write(contents);
    zip.closeEntry();
  }

  private static void addSource(ZipOutputStream zip, Source source, byte[] buffer)
      throws IOException {
    zip.putNextEntry(storedEntry(source.archivePath(), source.bytes(), source.crc32()));
    if (source.file() != null) {
      try (InputStream input = new BufferedInputStream(new FileInputStream(source.file()))) {
        int count;
        while ((count = input.read(buffer)) >= 0) {
          if (count > 0) {
            zip.write(buffer, 0, count);
          }
        }
      }
    } else {
      zip.write(source.generatedContents());
    }
    zip.closeEntry();
  }

  private static ZipEntry storedEntry(String name, long bytes, long crc32) {
    ZipEntry entry = new ZipEntry(name);
    entry.setMethod(ZipEntry.STORED);
    entry.setSize(bytes);
    entry.setCompressedSize(bytes);
    entry.setCrc(crc32);
    entry.setTime(0);
    return entry;
  }

  private static void atomicReplace(File temporary, File destination) throws IOException {
    try {
      Files.move(
          temporary.toPath(),
          destination.toPath(),
          StandardCopyOption.ATOMIC_MOVE,
          StandardCopyOption.REPLACE_EXISTING);
    } catch (AtomicMoveNotSupportedException unsupported) {
      Files.move(
          temporary.toPath(), destination.toPath(), StandardCopyOption.REPLACE_EXISTING);
    }
  }
}
