"""Run a bounded cold/warm/incremental Bazel profiling session safely."""

from __future__ import annotations

import argparse
import contextlib
import dataclasses
import fcntl
import hashlib
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING, final

if TYPE_CHECKING:
    from collections.abc import Callable, Generator, Mapping, Sequence
    from typing import TypeAlias

    CommandRunner: TypeAlias = Callable[[Sequence[str], Path], int]


DEFAULT_JOBS = 4
DEFAULT_MEMORY_MIB = 8192
DEFAULT_SERVER_HEAP_MIB = 3072
DEFAULT_TOTAL_WORKER_MEMORY_MIB = 4096
SERVER_IDLE_SECONDS = 5
PROFILE_TASKS = "local_action_counts"
PROFILE_NAME_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]*$")
SUPPORTED_COMMANDS = frozenset(("build", "test"))
JAVA_BYTECODE_STAGE = "incremental_java_bytecode"
SOURCE_ONLY_STAGE = "incremental_source_only"
COMMENT_PREFIX_BY_SUFFIX: Mapping[str, str] = {
    ".bzl": "#",
    ".cc": "//",
    ".cpp": "//",
    ".h": "//",
    ".hh": "//",
    ".java": "//",
    ".kt": "//",
    ".py": "#",
    ".ts": "//",
    ".tsx": "//",
}
FORBIDDEN_COMMAND_OPTIONS = (
    "--build_event_json_file",
    "--experimental_total_worker_memory_limit_mb",
    "--jobs",
    "--local_ram_resources",
    "--local_resources",
    "--profile",
    "--worker_max_instances",
)


@dataclasses.dataclass(frozen=True)
class ResourcePolicy:
    """Bound one isolated Bazel server and its concurrently scheduled actions."""

    jobs: int = DEFAULT_JOBS
    memory_mib: int = DEFAULT_MEMORY_MIB
    server_heap_mib: int = DEFAULT_SERVER_HEAP_MIB
    total_worker_memory_mib: int = DEFAULT_TOTAL_WORKER_MEMORY_MIB

    def validate(self) -> None:
        """Reject resource settings which cannot establish positive bounds."""
        values = (
            ("jobs", self.jobs),
            ("memory-mib", self.memory_mib),
            ("server-heap-mib", self.server_heap_mib),
            ("total-worker-memory-mib", self.total_worker_memory_mib),
        )
        for name, value in values:
            if value <= 0:
                message = f"{name} must be positive"
                raise ValueError(message)


@dataclasses.dataclass(frozen=True)
class ProfilePaths:
    """Name the durable evidence generated by one profile stage."""

    profile: Path
    bep: Path


@dataclasses.dataclass(frozen=True)
class ProfileSession:
    """Describe one cold/warm/incremental comparison."""

    root: Path
    bazel: str
    output_base: Path
    evidence_directory: Path
    name: str
    incremental_source: Path
    bazel_arguments: Sequence[str]
    policy: ResourcePolicy


@final
class ProfileCommandError(RuntimeError):
    """Report a failed Bazel stage without losing its evidence files."""

    def __init__(self, stage: str, exit_code: int) -> None:
        """Record the failing stage and client exit code."""
        super().__init__(f"Bazel {stage} profile failed with exit code {exit_code}")
        self.stage = stage
        self.exit_code = exit_code


def repository_root(environment: Mapping[str, str], current_directory: Path) -> Path:
    """Locate the workspace used to launch the Bazel-owned tool."""
    workspace = environment.get("BUILD_WORKSPACE_DIRECTORY")
    if workspace:
        return Path(workspace).resolve()

    candidate = current_directory.resolve()
    for directory in (candidate, *candidate.parents):
        if (directory / "MODULE.bazel").is_file():
            return directory
    invocation = "'bazel run //tools:bazel_iteration_profile -- ...'"
    message = f"cannot locate the repository; invoke with {invocation}"
    raise RuntimeError(message)


def resolve_from_workspace(root: Path, path: Path) -> Path:
    """Resolve a command-line path the same way from Bazel runfiles or a shell."""
    if path.is_absolute():
        return path.resolve()
    return (root / path).resolve()


def validate_profile_name(name: str) -> None:
    """Keep stage evidence names portable and unambiguous."""
    if not PROFILE_NAME_PATTERN.fullmatch(name):
        message = "name must contain only letters, digits, '.', '_', and '-'"
        raise ValueError(message)


def validate_bazel_arguments(arguments: Sequence[str]) -> None:
    """Prevent caller options from weakening or replacing enforced policy."""
    if not arguments or arguments[0] not in SUPPORTED_COMMANDS:
        supported = ", ".join(sorted(SUPPORTED_COMMANDS))
        message = f"profile command must start with one of: {supported}"
        raise ValueError(message)
    if "--" in arguments[1:]:
        message = "a second '--' is unsupported in a profiling command"
        raise ValueError(message)
    for argument in arguments[1:]:
        option = argument.split("=", maxsplit=1)[0]
        if option in FORBIDDEN_COMMAND_OPTIONS:
            message = f"{option} is managed by bazel_iteration_profile"
            raise ValueError(message)


def startup_arguments(output_base: Path, policy: ResourcePolicy) -> list[str]:
    """Return startup options shared by the work commands and shutdown client."""
    policy.validate()
    return [
        f"--output_base={output_base}",
        f"--max_idle_secs={SERVER_IDLE_SECONDS}",
        f"--host_jvm_args=-Xmx{policy.server_heap_mib}m",
    ]


def profile_paths(evidence_directory: Path, name: str, stage: str) -> ProfilePaths:
    """Derive deterministic evidence paths for one stage."""
    return ProfilePaths(
        profile=evidence_directory / f"{name}_{stage}.profile.gz",
        bep=evidence_directory / f"{name}_{stage}.bep.json",
    )


def bazel_profile_command(
    bazel: str,
    output_base: Path,
    evidence: ProfilePaths,
    bazel_arguments: Sequence[str],
    policy: ResourcePolicy,
) -> list[str]:
    """Construct one command with non-overridable resource and evidence options."""
    validate_bazel_arguments(bazel_arguments)
    command, *arguments = bazel_arguments
    return [
        bazel,
        *startup_arguments(output_base, policy),
        command,
        *arguments,
        f"--jobs={policy.jobs}",
        f"--local_resources=memory={policy.memory_mib}",
        f"--worker_max_instances={policy.jobs}",
        (f"--experimental_total_worker_memory_limit_mb={policy.total_worker_memory_mib}"),
        f"--profile={evidence.profile}",
        f"--build_event_json_file={evidence.bep}",
        f"--experimental_profile_additional_tasks={PROFILE_TASKS}",
    ]


def bazel_shutdown_command(bazel: str, output_base: Path, policy: ResourcePolicy) -> list[str]:
    """Construct a client command which addresses exactly the profiled server."""
    return [bazel, *startup_arguments(output_base, policy), "shutdown"]


def _default_command_runner(command: Sequence[str], root: Path) -> int:
    completed = subprocess.run(command, cwd=root, check=False)
    return completed.returncode


def _lock_path(root: Path) -> Path:
    identity = hashlib.sha256(os.fsencode(root)).hexdigest()[:16]
    return Path(tempfile.gettempdir()) / f"swing-capture-bazel-profile-{identity}.lock"


@contextlib.contextmanager
def exclusive_profile_lock(root: Path) -> Generator[None]:
    """Prevent concurrent isolated profile sessions for the same workspace."""
    path = _lock_path(root)
    with path.open("a+", encoding="utf-8") as lock:
        try:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError as error:
            message = f"another Bazel profile session owns {path}"
            raise RuntimeError(message) from error
        try:
            yield
        finally:
            fcntl.flock(lock, fcntl.LOCK_UN)


def _comment_prefix(source: Path) -> str:
    try:
        return COMMENT_PREFIX_BY_SUFFIX[source.suffix.lower()]
    except KeyError as error:
        supported = ", ".join(sorted(COMMENT_PREFIX_BY_SUFFIX))
        message = f"incremental source must use a supported suffix: {supported}"
        raise ValueError(message) from error


def incremental_stage(source: Path) -> str:
    """Name whether an incremental profile changes outputs or only source inputs."""
    if source.suffix.lower() == ".java":
        if source.name in {"module-info.java", "package-info.java"}:
            message = f"Java bytecode profiling does not support {source.name}"
            raise ValueError(message)
        return JAVA_BYTECODE_STAGE
    _comment_prefix(source)
    return SOURCE_ONLY_STAGE


def validate_incremental_source(root: Path, source: Path) -> None:
    """Require a regular, repository-contained source file for temporary editing."""
    try:
        source.relative_to(root)
    except ValueError as error:
        message = "incremental source must be inside the repository"
        raise ValueError(message) from error
    if source.is_symlink() or not source.is_file():
        message = "incremental source must be a regular, non-symlink file"
        raise ValueError(message)


@contextlib.contextmanager
def _temporary_incremental_append(root: Path, source: Path, marker: bytes) -> Generator[None]:
    """Append one unique marker and restore exact bytes unless another edit intervenes."""
    validate_incremental_source(root, source)
    original = source.read_bytes()
    separator = b"" if not original or original.endswith(b"\n") else b"\n"
    if marker in original:
        message = f"temporary marker already exists in {source}"
        raise RuntimeError(message)
    appended = separator + marker
    modified = original + appended
    try:
        with source.open("ab") as output:
            output.write(appended)
            output.flush()
            os.fsync(output.fileno())
    except OSError:
        # Appending never overwrites original bytes, so a partial write can be
        # recovered by returning to the previously observed length.
        with source.open("r+b") as output:
            output.truncate(len(original))
        raise
    try:
        yield
    finally:
        current = source.read_bytes()
        if current != modified:
            message = (
                f"{source} changed concurrently; refusing to overwrite it while removing "
                "the incremental marker"
            )
            raise RuntimeError(message)
        with source.open("r+b") as output:
            output.truncate(len(original))
            output.flush()
            os.fsync(output.fileno())


@contextlib.contextmanager
def temporary_incremental_comment(root: Path, source: Path) -> Generator[None]:
    """Append a source-only comment and restore the exact original bytes."""
    marker = (
        f"{_comment_prefix(source)} bazel_iteration_profile temporary incremental marker\n"
    ).encode()
    with _temporary_incremental_append(root, source, marker):
        yield


@contextlib.contextmanager
def temporary_incremental_java_bytecode(root: Path, source: Path) -> Generator[None]:
    """Append one unreferenced Java class so downstream bytecode actions are invalidated."""
    if incremental_stage(source) != JAVA_BYTECODE_STAGE:
        message = "Java bytecode profiling requires an ordinary .java source"
        raise ValueError(message)
    relative_source = source.relative_to(root)
    identity = hashlib.sha256(os.fsencode(relative_source)).hexdigest()[:16]
    marker = (f"final class BazelIterationProfileTemporaryMarker_{identity} {{}}\n").encode()
    with _temporary_incremental_append(root, source, marker):
        yield


@contextlib.contextmanager
def temporary_incremental_change(root: Path, source: Path) -> Generator[None]:
    """Apply the strongest safe incremental mutation supported for one source."""
    if incremental_stage(source) == JAVA_BYTECODE_STAGE:
        with temporary_incremental_java_bytecode(root, source):
            yield
        return
    with temporary_incremental_comment(root, source):
        yield


def _validate_new_paths(
    output_base: Path,
    evidence_directory: Path,
    name: str,
    incremental_stage_name: str,
) -> None:
    if output_base.exists():
        message = f"cold profile output base already exists: {output_base}"
        raise FileExistsError(message)
    expected = [
        path
        for stage in ("cold", "warm", incremental_stage_name)
        for path in (
            profile_paths(evidence_directory, name, stage).profile,
            profile_paths(evidence_directory, name, stage).bep,
        )
    ]
    existing = [path for path in expected if path.exists()]
    if existing:
        message = f"profile evidence already exists: {existing[0]}"
        raise FileExistsError(message)


def run_profile_session(
    session: ProfileSession,
    command_runner: CommandRunner = _default_command_runner,
) -> None:
    """Run three comparable stages, then shut down their one isolated server."""
    validate_profile_name(session.name)
    validate_bazel_arguments(session.bazel_arguments)
    session.policy.validate()
    validate_incremental_source(session.root, session.incremental_source)
    incremental_stage_name = incremental_stage(session.incremental_source)

    with exclusive_profile_lock(session.root):
        _validate_new_paths(
            session.output_base,
            session.evidence_directory,
            session.name,
            incremental_stage_name,
        )
        session.evidence_directory.mkdir(parents=True, exist_ok=True)
        shutdown_failed = False
        try:
            for stage in ("cold", "warm"):
                evidence = profile_paths(session.evidence_directory, session.name, stage)
                exit_code = command_runner(
                    bazel_profile_command(
                        session.bazel,
                        session.output_base,
                        evidence,
                        session.bazel_arguments,
                        session.policy,
                    ),
                    session.root,
                )
                if exit_code != 0:
                    raise ProfileCommandError(stage, exit_code)

            with temporary_incremental_change(session.root, session.incremental_source):
                stage = incremental_stage_name
                evidence = profile_paths(session.evidence_directory, session.name, stage)
                exit_code = command_runner(
                    bazel_profile_command(
                        session.bazel,
                        session.output_base,
                        evidence,
                        session.bazel_arguments,
                        session.policy,
                    ),
                    session.root,
                )
                if exit_code != 0:
                    raise ProfileCommandError(stage, exit_code)
        finally:
            shutdown_failed = (
                command_runner(
                    bazel_shutdown_command(
                        session.bazel,
                        session.output_base,
                        session.policy,
                    ),
                    session.root,
                )
                != 0
            )
        if shutdown_failed:
            message = f"failed to shut down Bazel server in {session.output_base}"
            raise RuntimeError(message)


def _positive_integer(value: str) -> int:
    parsed = int(value)
    if parsed <= 0:
        message = "value must be positive"
        raise argparse.ArgumentTypeError(message)
    return parsed


class _Arguments(argparse.Namespace):
    """Typed command-line values produced by the profile parser."""

    def __init__(self) -> None:
        """Initialize defaults that argparse replaces while parsing."""
        super().__init__()
        self.output_base: Path = Path()
        self.evidence_dir: Path = Path()
        self.name: str = ""
        self.incremental_file: Path = Path()
        self.bazel: str = "bazel"
        self.jobs: int = DEFAULT_JOBS
        self.memory_mib: int = DEFAULT_MEMORY_MIB
        self.server_heap_mib: int = DEFAULT_SERVER_HEAP_MIB
        self.total_worker_memory_mib: int = DEFAULT_TOTAL_WORKER_MEMORY_MIB
        self.bazel_arguments: list[str] = []


def _parse_arguments(arguments: Sequence[str]) -> _Arguments:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-base", required=True, type=Path)
    parser.add_argument("--evidence-dir", required=True, type=Path)
    parser.add_argument("--name", required=True)
    parser.add_argument("--incremental-file", required=True, type=Path)
    parser.add_argument("--bazel", default="bazel")
    parser.add_argument("--jobs", default=DEFAULT_JOBS, type=_positive_integer)
    parser.add_argument("--memory-mib", default=DEFAULT_MEMORY_MIB, type=_positive_integer)
    parser.add_argument(
        "--server-heap-mib",
        default=DEFAULT_SERVER_HEAP_MIB,
        type=_positive_integer,
    )
    parser.add_argument(
        "--total-worker-memory-mib",
        default=DEFAULT_TOTAL_WORKER_MEMORY_MIB,
        type=_positive_integer,
    )
    parser.add_argument(
        "bazel_arguments",
        nargs=argparse.REMAINDER,
        help="Bazel command and arguments after '--'",
    )
    parsed = parser.parse_args(arguments, namespace=_Arguments())
    if parsed.bazel_arguments[:1] == ["--"]:
        parsed.bazel_arguments = parsed.bazel_arguments[1:]
    return parsed


def main(arguments: Sequence[str] | None = None) -> int:
    """Parse one safe profile session and return a conventional process status."""
    parsed = _parse_arguments(arguments if arguments is not None else sys.argv[1:])
    root = repository_root(os.environ, Path.cwd())
    policy = ResourcePolicy(
        jobs=parsed.jobs,
        memory_mib=parsed.memory_mib,
        server_heap_mib=parsed.server_heap_mib,
        total_worker_memory_mib=parsed.total_worker_memory_mib,
    )
    try:
        session = ProfileSession(
            root=root,
            bazel=parsed.bazel,
            output_base=resolve_from_workspace(root, parsed.output_base),
            evidence_directory=resolve_from_workspace(root, parsed.evidence_dir),
            name=parsed.name,
            incremental_source=resolve_from_workspace(root, parsed.incremental_file),
            bazel_arguments=parsed.bazel_arguments,
            policy=policy,
        )
        run_profile_session(session)
    except (OSError, RuntimeError, ValueError) as error:
        print(f"bazel_iteration_profile: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
