name: Bazel presubmit

on:
  pull_request:
  push:

permissions:
  contents: read

concurrency:
  group: bazel-presubmit-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Bazel test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86 # v0.19.0
        with:
          bazelisk-cache: true
          disk-cache: bazel-presubmit
          repository-cache: true
          cache-save: ${{ github.event_name != 'pull_request' }}
      - name: Test and check Bazel targets
        run: bazel test //... --test_output=errors
